[build]
builder = "dockerfile"
dockerfilePath = "demo-services/order/Dockerfile"
watchPatterns = [
  "demo-services/order/**",
  "backend/common/**",
  "pom.xml"
]

[deploy]
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 10

