[build]
builder = "dockerfile"
dockerfilePath = "backend/api-gateway/Dockerfile"
watchPatterns = [
  "backend/api-gateway/**",
  "backend/common/**",
  "pom.xml"
]

[deploy]
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 10

